/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8VfATpvSoh3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Caudex } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

caudex({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  const dresses = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Floral Midi Dress",
      price: "$79.99",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Linen Wrap Dress",
      price: "$59.99",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Pleated Maxi Dress",
      price: "$99.99",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Polka Dot Sundress",
      price: "$49.99",
    },
  ]
  const shoes = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Leather Sandals",
      price: "$59.99",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Canvas Sneakers",
      price: "$39.99",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Suede Loafers",
      price: "$79.99",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Strappy Heels",
      price: "$89.99",
    },
  ]
  const tops = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Silk Blouse",
      price: "$49.99",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Striped Tee",
      price: "$29.99",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Linen Button-up",
      price: "$59.99",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Ruffle Camisole",
      price: "$39.99",
    },
  ]
  const bottoms = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Denim Shorts",
      price: "$39.99",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Linen Trousers",
      price: "$69.99",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Pleated Skirt",
      price: "$49.99",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Chino Pants",
      price: "$59.99",
    },
  ]
  const [activeSection, setActiveSection] = useState("dresses")
  const handleSectionClick = (section) => {
    setActiveSection(section)
  }
  return (
    <div className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12">
      <div className="flex items-center justify-between mb-8">
        <h1 className="text-3xl font-bold">Shop by Category</h1>
        <div className="flex gap-4">
          <Button
            variant={activeSection === "dresses" ? "primary" : "outline"}
            onClick={() => handleSectionClick("dresses")}
          >
            Dresses
          </Button>
          <Button
            variant={activeSection === "shoes" ? "primary" : "outline"}
            onClick={() => handleSectionClick("shoes")}
          >
            Shoes
          </Button>
          <Button variant={activeSection === "tops" ? "primary" : "outline"} onClick={() => handleSectionClick("tops")}>
            Tops
          </Button>
          <Button
            variant={activeSection === "bottoms" ? "primary" : "outline"}
            onClick={() => handleSectionClick("bottoms")}
          >
            Bottoms
          </Button>
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
        {activeSection === "dresses" &&
          dresses.map((dress) => (
            <div
              key={dress.id}
              className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-all duration-300 ease-in-out"
            >
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View</span>
              </Link>
              <img
                src="/placeholder.svg"
                alt={dress.title}
                width={400}
                height={500}
                className="object-cover w-full h-64"
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">{dress.title}</h3>
                <p className="text-lg font-semibold">{dress.price}</p>
              </div>
            </div>
          ))}
        {activeSection === "shoes" &&
          shoes.map((shoe) => (
            <div
              key={shoe.id}
              className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-all duration-300 ease-in-out"
            >
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View</span>
              </Link>
              <img
                src="/placeholder.svg"
                alt={shoe.title}
                width={400}
                height={500}
                className="object-cover w-full h-64"
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">{shoe.title}</h3>
                <p className="text-lg font-semibold">{shoe.price}</p>
              </div>
            </div>
          ))}
        {activeSection === "tops" &&
          tops.map((top) => (
            <div
              key={top.id}
              className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-all duration-300 ease-in-out"
            >
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View</span>
              </Link>
              <img
                src="/placeholder.svg"
                alt={top.title}
                width={400}
                height={500}
                className="object-cover w-full h-64"
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">{top.title}</h3>
                <p className="text-lg font-semibold">{top.price}</p>
              </div>
            </div>
          ))}
        {activeSection === "bottoms" &&
          bottoms.map((bottom) => (
            <div
              key={bottom.id}
              className="relative overflow-hidden rounded-lg shadow-lg group hover:shadow-xl hover:-translate-y-2 transition-all duration-300 ease-in-out"
            >
              <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                <span className="sr-only">View</span>
              </Link>
              <img
                src="/placeholder.svg"
                alt={bottom.title}
                width={400}
                height={500}
                className="object-cover w-full h-64"
              />
              <div className="p-4 bg-background">
                <h3 className="text-xl font-bold">{bottom.title}</h3>
                <p className="text-lg font-semibold">{bottom.price}</p>
              </div>
            </div>
          ))}
      </div>
    </div>
  )
}
